spring.application.name=S05T01
# MongoDB
spring.data.mongodb.uri=${MONGODB_URI}
# R2DBC connection
spring.r2dbc.url=${R2DBC_URL}
spring.r2dbc.username=${R2DBC_USERNAME}
spring.r2dbc.password=${R2DBC_PASSWORD}
spring.sql.init.mode=always
spring.sql.init.platform=mysql
#BlackJackConfiguration
blackjack.dev.betMin=5
blackjack.dev.betMax=100
blackjack.dev.noDoubleSplitWithAs=true
blackjack.dev.numPlayerMax=20