on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u aurelien-darbellay --password-stdin

      - name: Build image
        run: docker build -t ghcr.io/aurelien-darbellay/s05t01:latest .

      - name: Push image
        run: docker push ghcr.io/aurelien-darbellay/s05t01:latest

      - name: Trigger Render deploy
        run: curl -X POST https://api.render.com/deploy/srv-d0isr0h5pdvs739r6v00?key=${{ secrets.RENDER_DEPLOY_HOOK }}
